# This is a basic workflow to help you get started with Actions

name: Deploy to ECR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 952528942962.dkr.ecr.us-east-1.amazonaws.com/demoreactapp
    - name: TOKEN=`aws ecr get-login-password --region us-east-1 | cut -d' ' -f6
      run: echo $TOKEN  
    - name: Build Docker Image
      run: docker build -t demoreactapp .
      working-directory: .
    - name: tagging to image
      run: docker tag demoreactapp:latest 952528942962.dkr.ecr.us-east-1.amazonaws.com/demoreactapp:latest  
    - name: Push Docker Image to ECR
      run: docker push 952528942962.dkr.ecr.us-east-1.amazonaws.com/demoreactapp:latest


    # - name: Build, tag, and push image to Amazon ECR
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #     ECR_REPOSITORY: demoreactapp
    #     IMAGE_TAG: latest
    #   run: |
    #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
 
 
 
 
 
 
 
 
    # - name: Login to Amazon ECR
    #   run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 952528942962.dkr.ecr.us-east-1.amazonaws.com/demoreactapp
    # - name: Build Docker Image
    #   run: docker build -t react-app:latest .
    #   working-directory: .
    # - name: Push Docker Image to ECR
    #   run: docker push 952528942962.dkr.ecr.us-east-1.amazonaws.com/demoreactapp:latest
