name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases

  push-to-ecr:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 952528942962.dkr.ecr.us-east-1.amazonaws.com/demoreactapp
    - name: Build Docker Image
      run: docker build -t react-app:latest --file Dockerfile
      working-directory: .
    - name: Push Docker Image to ECR
      run: docker push 952528942962.dkr.ecr.us-east-1.amazonaws.com/demoreactapp:latest
