# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install NPM
      run: npm install
    - name: npm build
      run: npm run build

    
    



 




# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Install dependencies and build
#         run: |
#           npm install
#           npm run build

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: your-region

#       - name: Login to Amazon ECR
#         id: login-ecr
#         run: aws ecr get-login-password --region us-east-1 | docker login --username root --password-stdin 493925731629.dkr.ecr.us-east-1.amazonaws.com

#       - name: Tag Docker image
#         run: docker tag react-app:latest 493925731629.dkr.ecr.us-east-1.amazonaws.com/learn-reactapp:latest

#       - name: Push Docker image to Amazon ECR
#         run: docker push 493925731629.dkr.ecr.us-east-1.amazonaws.com/learn-reactapp:latest

#       # Continue with deploying to Kubernetes using Helm or other methods
